/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import DAO.VehiculoDAO;
import java.util.List;

/**
 *
 * @author nicop
 */
public class CrearVehiculo extends javax.swing.JFrame {

    private VehiculoDAO vehiculoDAO = new VehiculoDAO();

    /**
     * Creates new form MenuCrear
     */
    public CrearVehiculo() {
        initComponents();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tfMatriculaNueva = new javax.swing.JTextField();
        tfAnyoNueva = new javax.swing.JTextField();
        cbMarcaNueva = new javax.swing.JComboBox<>();
        cbModeloNueva = new javax.swing.JComboBox<>();
        bOkNuevo = new javax.swing.JButton();
        bCancelarNuevo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Matricula:");

        jLabel2.setText("Año:");

        jLabel3.setText("Marca:");

        jLabel4.setText("Modelo:");

        cbMarcaNueva.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Audi", "BMW", "Chevrolet", "Ford", "Honda", "Hyundai", "Kia", "Mazda", "Mercedes-Benz", "Nissan", "Toyota", "Volkswagen" }));
        cbMarcaNueva.setName("Añadir vehículo"); // NOI18N
        cbMarcaNueva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMarcaNuevaActionPerformed(evt);
            }
        });

        cbModeloNueva.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbModeloNueva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbModeloNuevaActionPerformed(evt);
            }
        });

        bOkNuevo.setText("OK");

        bCancelarNuevo.setText("Cancel");
        bCancelarNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelarNuevoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfMatriculaNueva)
                            .addComponent(tfAnyoNueva)
                            .addComponent(cbMarcaNueva, 0, 110, Short.MAX_VALUE)
                            .addComponent(cbModeloNueva, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bOkNuevo)
                        .addGap(18, 18, 18)
                        .addComponent(bCancelarNuevo)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfMatriculaNueva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfAnyoNueva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbMarcaNueva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbModeloNueva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bOkNuevo)
                    .addComponent(bCancelarNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbMarcaNuevaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMarcaNuevaActionPerformed
        String selectedMarca = (String) cbMarcaNueva.getSelectedItem();
        if (selectedMarca != null && !selectedMarca.isEmpty()) {
            cargarModelos(selectedMarca); // Cargar los modelos correspondientes a la marca seleccionada
        }
    }//GEN-LAST:event_cbMarcaNuevaActionPerformed

    private void bCancelarNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelarNuevoActionPerformed
        dispose();
    }//GEN-LAST:event_bCancelarNuevoActionPerformed

    private void cbModeloNuevaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbModeloNuevaActionPerformed
        String selectedMarca = (String) cbMarcaNueva.getSelectedItem();
        if (selectedMarca != null && !selectedMarca.isEmpty()) {
            // Cargar los modelos correspondientes a la marca seleccionada
            cargarModelos(selectedMarca);
        }
    }//GEN-LAST:event_cbModeloNuevaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrearVehiculo().setVisible(true);
            }
        });
    }

    private void cargarMarcas() {
        // Llama al DAO para obtener todas las marcas y llenar el JComboBox
        List<String> marcas = vehiculoDAO.obtenerMarcas();
        cbMarcaNueva.removeAllItems(); // Limpia los elementos anteriores

        // Añadir las marcas al JComboBox
        for (String marca : marcas) {
            cbMarcaNueva.addItem(marca);
        }
    }

    private void cargarModelos(String marca) {
        // Llama al DAO para obtener todos los modelos de la marca seleccionada
        List<String> modelos = vehiculoDAO.obtenerModelosPorMarca(marca);
        cbModeloNueva.removeAllItems(); // Limpia los elementos anteriores

        // Añadir los modelos al JComboBox
        for (String modelo : modelos) {
            cbModeloNueva.addItem(modelo);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCancelarNuevo;
    private javax.swing.JButton bOkNuevo;
    private javax.swing.JComboBox<String> cbMarcaNueva;
    private javax.swing.JComboBox<String> cbModeloNueva;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField tfAnyoNueva;
    private javax.swing.JTextField tfMatriculaNueva;
    // End of variables declaration//GEN-END:variables
}
