/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controlador.PersonaVehiculoController;
import java.awt.Color;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Dankrani
 */
public class Vista extends javax.swing.JFrame {

    private boolean pulsado = false;

    private String[] nomColumnas = {"Nombre", "Matricula", "Modelo", "Marca", "Año", "Ant. Prop."};
    private Object[][] matrizDatos;

    private DefaultTableModel dtm = new DefaultTableModel(matrizDatos, nomColumnas);

    /**
     * Creates new form Vista
     */
    public Vista() {
        initComponents();
        jlModelo.setVisible(false);
        jlAnoMatricu.setVisible(false);
        jlNumVehiculos.setVisible(false);
        cbModelos.setVisible(false);
        tfAnoMatriculacion.setVisible(false);
        tfNumVehiculos.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jlNombre = new javax.swing.JLabel();
        tfNombre = new javax.swing.JTextField();
        jrHombre = new javax.swing.JRadioButton();
        jrMujer = new javax.swing.JRadioButton();
        cbMarcas = new javax.swing.JComboBox<>();
        jbAplicarFiltros = new javax.swing.JButton();
        jlModelo = new javax.swing.JLabel();
        cbModelos = new javax.swing.JComboBox<>();
        jlAnoMatricu = new javax.swing.JLabel();
        tfAnoMatriculacion = new javax.swing.JTextField();
        jlNumVehiculos = new javax.swing.JLabel();
        tfNumVehiculos = new javax.swing.JTextField();
        jbAvanzados = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuRaiz = new javax.swing.JMenu();
        jMenuItemCrear = new javax.swing.JMenuItem();
        jMenuItemAsociar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jPanel1PropertyChange(evt);
            }
        });

        jlNombre.setText("Nombre:");

        tfNombre.setText("jTextField1");

        buttonGroup1.add(jrHombre);
        jrHombre.setText("Hombre");
        jrHombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrHombreActionPerformed(evt);
            }
        });

        buttonGroup1.add(jrMujer);
        jrMujer.setText("Mujer");

        cbMarcas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Audi", "BMW", "Chevrolet", "Ford", "Honda", "Hyundai", "Kia", "Mazda", "Mercedes-Benz", "Nissan", "Toyota", "Volkswagen" }));

        jbAplicarFiltros.setText("Aplicar filtros");
        jbAplicarFiltros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAplicarFiltrosActionPerformed(evt);
            }
        });

        jlModelo.setText("Modelo:");

        cbModelos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jlAnoMatricu.setText("Año de matriculación:");

        tfAnoMatriculacion.setText("jTextField1");
        tfAnoMatriculacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfAnoMatriculacionActionPerformed(evt);
            }
        });

        jlNumVehiculos.setText("Nº de veículos:");

        tfNumVehiculos.setText("jTextField1");

        jbAvanzados.setText("Filtros avanzados");
        jbAvanzados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAvanzadosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jlModelo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cbModelos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jlAnoMatricu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfAnoMatriculacion, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jlNumVehiculos)
                        .addGap(16, 16, 16))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jrHombre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jrMujer)
                        .addGap(18, 18, 18)
                        .addComponent(cbMarcas, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jbAvanzados)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbAplicarFiltros))
                    .addComponent(tfNumVehiculos, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlNombre)
                    .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jrHombre)
                    .addComponent(jrMujer)
                    .addComponent(cbMarcas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbAplicarFiltros)
                    .addComponent(jbAvanzados))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlModelo)
                    .addComponent(cbModelos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlAnoMatricu)
                    .addComponent(tfAnoMatriculacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlNumVehiculos)
                    .addComponent(tfNumVehiculos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Mostrar registros");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 722, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenuRaiz.setText("Opciones");

        jMenuItemCrear.setText("Crear vehiculo");
        jMenuItemCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCrearActionPerformed(evt);
            }
        });
        jMenuRaiz.add(jMenuItemCrear);

        jMenuItemAsociar.setText("Asociar vehículo");
        jMenuRaiz.add(jMenuItemAsociar);

        jMenuBar1.add(jMenuRaiz);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jPanel1PropertyChange
        jPanel1.setSize(713, 83);
    }//GEN-LAST:event_jPanel1PropertyChange

    private void jbAvanzadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAvanzadosActionPerformed
//        boolean pulsado = false;

        // NO SE OCULTA
        // HAY QUE MIRARLO
        if (!pulsado) {
            pulsado = true;
            jbAvanzados.setBackground(Color.black);
            jbAvanzados.setForeground(Color.white);
            jlModelo.setVisible(pulsado);
            jlAnoMatricu.setVisible(pulsado);
            jlNumVehiculos.setVisible(pulsado);
            cbModelos.setVisible(pulsado);
            tfAnoMatriculacion.setVisible(pulsado);
            tfNumVehiculos.setVisible(pulsado);
        } else if (pulsado) {
            pulsado = false;
            jbAvanzados.setBackground(Color.white);
            jbAvanzados.setForeground(Color.black);
            jlModelo.setVisible(pulsado);
            jlAnoMatricu.setVisible(pulsado);
            jlNumVehiculos.setVisible(pulsado);
            cbModelos.setVisible(pulsado);
            tfAnoMatriculacion.setVisible(pulsado);
            tfNumVehiculos.setVisible(pulsado);
        }

    }//GEN-LAST:event_jbAvanzadosActionPerformed

    private void jMenuItemCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCrearActionPerformed
        //TODO
    }//GEN-LAST:event_jMenuItemCrearActionPerformed

    private void jrHombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrHombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrHombreActionPerformed

    private void jbAplicarFiltrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAplicarFiltrosActionPerformed

    }//GEN-LAST:event_jbAplicarFiltrosActionPerformed

    private void tfAnoMatriculacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfAnoMatriculacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfAnoMatriculacionActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int filaSeleccionada = jTable1.getSelectedRow();
        if (filaSeleccionada != -1) {
            // Obtener la matrícula de la fila seleccionada
            String matricula = (String) jTable1.getValueAt(filaSeleccionada, 1);

            // Llama al controlador para mostrar los detalles del vehículo
            PersonaVehiculoController.mostrarDetallesVehiculo(matricula);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbMarcas;
    private javax.swing.JComboBox<String> cbModelos;
    private javax.swing.JButton jButton1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemAsociar;
    private javax.swing.JMenuItem jMenuItemCrear;
    private javax.swing.JMenu jMenuRaiz;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbAplicarFiltros;
    private javax.swing.JButton jbAvanzados;
    private javax.swing.JLabel jlAnoMatricu;
    private javax.swing.JLabel jlModelo;
    private javax.swing.JLabel jlNombre;
    private javax.swing.JLabel jlNumVehiculos;
    private javax.swing.JRadioButton jrHombre;
    private javax.swing.JRadioButton jrMujer;
    private javax.swing.JTextField tfAnoMatriculacion;
    private javax.swing.JTextField tfNombre;
    private javax.swing.JTextField tfNumVehiculos;
    // End of variables declaration//GEN-END:variables

    public boolean isPulsado() {
        return pulsado;
    }

    public void setPulsado(boolean pulsado) {
        this.pulsado = pulsado;
    }

    public String[] getNomColumnas() {
        return nomColumnas;
    }

    public void setNomColumnas(String[] nomColumnas) {
        this.nomColumnas = nomColumnas;
    }

    public Object[][] getMatrizDatos() {
        return matrizDatos;
    }

    public void setMatrizDatos(Object[][] matrizDatos) {
        this.matrizDatos = matrizDatos;
    }

    public DefaultTableModel getDtm() {
        return dtm;
    }

    public void setDtm(DefaultTableModel dtm) {
        this.dtm = dtm;
    }

    public javax.swing.ButtonGroup getButtonGroup1() {
        return buttonGroup1;
    }

    public void setButtonGroup1(javax.swing.ButtonGroup buttonGroup1) {
        this.buttonGroup1 = buttonGroup1;
    }

    public javax.swing.JComboBox<String> getCbMarcas() {
        return cbMarcas;
    }

    public void setCbMarcas(javax.swing.JComboBox<String> cbMarcas) {
        this.cbMarcas = cbMarcas;
    }

    public javax.swing.JComboBox<String> getCbModelos() {
        return cbModelos;
    }

    public void setCbModelos(javax.swing.JComboBox<String> cbModelos) {
        this.cbModelos = cbModelos;
    }

    public javax.swing.JButton getjButton1() {
        return jButton1;
    }

    public void setjButton1(javax.swing.JButton jButton1) {
        this.jButton1 = jButton1;
    }

    public javax.swing.JMenuBar getjMenuBar1() {
        return jMenuBar1;
    }

    public void setjMenuBar1(javax.swing.JMenuBar jMenuBar1) {
        this.jMenuBar1 = jMenuBar1;
    }

    public javax.swing.JMenuItem getjMenuItemAsociar() {
        return jMenuItemAsociar;
    }

    public void setjMenuItemAsociar(javax.swing.JMenuItem jMenuItemAsociar) {
        this.jMenuItemAsociar = jMenuItemAsociar;
    }

    public javax.swing.JMenuItem getjMenuItemCrear() {
        return jMenuItemCrear;
    }

    public void setjMenuItemCrear(javax.swing.JMenuItem jMenuItemCrear) {
        this.jMenuItemCrear = jMenuItemCrear;
    }

    public javax.swing.JMenu getjMenuRaiz() {
        return jMenuRaiz;
    }

    public void setjMenuRaiz(javax.swing.JMenu jMenuRaiz) {
        this.jMenuRaiz = jMenuRaiz;
    }

    public javax.swing.JPanel getjPanel1() {
        return jPanel1;
    }

    public void setjPanel1(javax.swing.JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }

    public javax.swing.JPanel getjPanel2() {
        return jPanel2;
    }

    public void setjPanel2(javax.swing.JPanel jPanel2) {
        this.jPanel2 = jPanel2;
    }

    public javax.swing.JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public void setjScrollPane1(javax.swing.JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    public javax.swing.JTable getjTable1() {
        return jTable1;
    }

    public void setjTable1(javax.swing.JTable jTable1) {
        this.jTable1 = jTable1;
    }

    public javax.swing.JButton getJbAplicarFiltros() {
        return jbAplicarFiltros;
    }

    public void setJbAplicarFiltros(javax.swing.JButton jbAplicarFiltros) {
        this.jbAplicarFiltros = jbAplicarFiltros;
    }

    public javax.swing.JButton getJbAvanzados() {
        return jbAvanzados;
    }

    public void setJbAvanzados(javax.swing.JButton jbAvanzados) {
        this.jbAvanzados = jbAvanzados;
    }

    public javax.swing.JLabel getJlAnoMatricu() {
        return jlAnoMatricu;
    }

    public void setJlAnoMatricu(javax.swing.JLabel jlAnoMatricu) {
        this.jlAnoMatricu = jlAnoMatricu;
    }

    public javax.swing.JLabel getJlModelo() {
        return jlModelo;
    }

    public void setJlModelo(javax.swing.JLabel jlModelo) {
        this.jlModelo = jlModelo;
    }

    public javax.swing.JLabel getJlNombre() {
        return jlNombre;
    }

    public void setJlNombre(javax.swing.JLabel jlNombre) {
        this.jlNombre = jlNombre;
    }

    public javax.swing.JLabel getJlNumVehiculos() {
        return jlNumVehiculos;
    }

    public void setJlNumVehiculos(javax.swing.JLabel jlNumVehiculos) {
        this.jlNumVehiculos = jlNumVehiculos;
    }

    public javax.swing.JRadioButton getJrHombre() {
        return jrHombre;
    }

    public void setJrHombre(javax.swing.JRadioButton jrHombre) {
        this.jrHombre = jrHombre;
    }

    public javax.swing.JRadioButton getJrMujer() {
        return jrMujer;
    }

    public void setJrMujer(javax.swing.JRadioButton jrMujer) {
        this.jrMujer = jrMujer;
    }

    public javax.swing.JTextField getTfAnoMatriculacion() {
        return tfAnoMatriculacion;
    }

    public void setTfAnoMatriculacion(javax.swing.JTextField tfAnoMatriculacion) {
        this.tfAnoMatriculacion = tfAnoMatriculacion;
    }

    public javax.swing.JTextField getTfNombre() {
        return tfNombre;
    }

    public void setTfNombre(javax.swing.JTextField tfNombre) {
        this.tfNombre = tfNombre;
    }

    public javax.swing.JTextField getTfNumVehiculos() {
        return tfNumVehiculos;
    }

    public void setTfNumVehiculos(javax.swing.JTextField tfNumVehiculos) {
        this.tfNumVehiculos = tfNumVehiculos;
    }
}
